<b> Imports and file paths </b>

In [5]:
from pathlib import Path
import pandas as pd

project_root = Path.cwd()

rahman_path = (
    project_root
    / "data"
    / "raw"
    / "constructed_dataset"
    / "Students_Performance_data_set.xlsx"
)

hasan_path = (
    project_root
    / "data"
    / "raw"
    / "constructed_dataset"
    / "ResearchInformation3.csv"
)

print("Project root:", project_root)
print("Rahman file exists:", rahman_path.exists())
print("Hasan file exists :", hasan_path.exists())

Project root: /Users/awais/Desktop/COMP8240_Project
Rahman file exists: True
Hasan file exists : True


<b> Load both datasets </b>

In [6]:
rahman = pd.read_excel(rahman_path)
hasan = pd.read_csv(hasan_path)

print("Rahman shape:", rahman.shape)
print("Hasan shape :", hasan.shape)

Rahman shape: (1194, 31)
Hasan shape : (493, 16)

<b> Rahman Data-set columns </b>

In [7]:
print("RAHMAN DATASET COLUMNS")
print("=" * 50)

for i, col in enumerate(rahman.columns, 1):
    print(f"{i:2}. {col}")

RAHMAN DATASET COLUMNS
==================================================
 1. University Admission year
 2. Gender
 3. Age
 4. H.S.C passing year
 5. Program
 6. Current Semester
 7. Do you have meritorious scholarship ?
 8. Do you use University transportation?
 9. How many hour do you study daily?
10. How many times do you seat for study in a day?
11. What is your preferable learning mode?
12. Do you use smart phone?
13. Do you have personal Computer?
14. How many hour do you spent daily in social media?
15. Status of your English language proficiency
16. Average attendance on class
17. Did you ever fall in probation?
18. Did you ever got suspension?
19. Do you attend in teacher consultancy for any kind of academical problems?
20. What are the skills do you have ?
21. How many hour do you spent daily on your skill development?
22. What is you interested area?
23. What is your relationship status?
24. Are you engaged with any co-curriculum activities?
25. With whom you are living with?
26. Do you have any health issues?
27. What was your previous SGPA?
28. Do you have any physical disabilities?
29. What is your current CGPA?
30. How many Credit did you have completed?
31. What is your monthly family income?

<b> Hasan data-set columns </b>

In [8]:
print("HASAN DATASET COLUMNS")
print("=" * 50)

for i, col in enumerate(hasan.columns, 1):
    print(f"{i:2}. {col}")

HASAN DATASET COLUMNS
==================================================
 1. Department
 2. Gender
 3. HSC
 4. SSC
 5. Income
 6. Hometown
 7. Computer
 8. Preparation
 9. Gaming
10. Attendance
11. Job
12. English
13. Extra
14. Semester
15. Last
16. Overall

<b> Previews both data-sets </b>

In [9]:
rahman.head()

,University Admission year,Gender,Age,H.S.C passing year,Program,Current Semester,Do you have meritorious scholarship ?,Do you use University transportation?,How many hour do you study daily?,How many times do you seat for study in a day?,...,What is you interested area?,What is your relationship status?,Are you engaged with any co-curriculum activities?,With whom you are living with?,Do you have any health issues?,What was your previous SGPA?,Do you have any physical disabilities?,What is your current CGPA?,How many Credit did you have completed?,What is your monthly family income?
0,2018,Male,24,2016,BCSE,12,Yes,No,3,2,...,Data Schince,Single,Yes,Bachelor,No,2.68,No,3.15,75,25000
1,2021,Male,22,2020,BCSE,4,Yes,Yes,3,2,...,Event management,Single,Yes,Family,No,2.68,No,3.15,36,100000
2,2020,Female,21,2019,BCSE,5,No,No,3,3,...,Software,Single,No,Bachelor,No,2.68,No,3.15,50,50000
3,2021,Male,20,2020,BCSE,4,Yes,No,1,3,...,Artificial Intelligence,Single,No,Bachelor,Yes,2.68,No,3.15,36,62488
4,2021,Male,22,2019,BCSE,4,Yes,No,3,1,...,Software,Relationship,No,Bachelor,Yes,2.68,No,3.15,36,50000

In [10]:
hasan.head()

,Department,Gender,HSC,SSC,Income,Hometown,Computer,Preparation,Gaming,Attendance,Job,English,Extra,Semester,Last,Overall
0,Business Administration,Male,4.17,4.84,"Low (Below 15,000)",Village,3,More than 3 Hours,0-1 Hour,80%-100%,No,3,Yes,6th,3.220,3.350
1,Business Administration,Female,4.92,5.00,"Upper middle (30,000-50,000)",City,3,0-1 Hour,0-1 Hour,80%-100%,No,3,Yes,7th,3.467,3.467
2,Business Administration,Male,5.00,4.83,"Lower middle (15,000-30,000)",Village,3,0-1 Hour,More than 3 Hours,80%-100%,No,4,Yes,3rd,4.000,3.720
3,Business Administration,Male,4.00,4.50,"High (Above 50,000)",City,5,More than 3 Hours,More than 3 Hours,80%-100%,No,5,Yes,4th,3.800,3.750
4,Business Administration,Female,2.19,3.17,"Lower middle (15,000-30,000)",Village,3,0-1 Hour,2-3 Hours,80%-100%,No,3,Yes,4th,3.940,3.940

<b> Quality checks </b>

In [11]:
print("RAHMAN DATASET")
print("Rows:", rahman.shape[0])
print("Columns:", rahman.shape[1])
print("Missing values:", rahman.isnull().sum().sum())
print("Duplicate rows:", rahman.duplicated().sum())

print("\nHASAN DATASET")
print("Rows:", hasan.shape[0])
print("Columns:", hasan.shape[1])
print("Missing values:", hasan.isnull().sum().sum())
print("Duplicate rows:", hasan.duplicated().sum())

RAHMAN DATASET
Rows: 1194
Columns: 31
Missing values: 1
Duplicate rows: 0

HASAN DATASET
Rows: 493
Columns: 16
Missing values: 0
Duplicate rows: 0

<b> Print exact Rahman columns </b>

In [12]:
print("RAHMAN COLUMNS")
print("=" * 60)

for i, col in enumerate(rahman.columns, 1):
    print(f"{i:2}. {repr(col)}")

RAHMAN COLUMNS
============================================================
 1. 'University Admission year'
 2. 'Gender'
 3. 'Age'
 4. 'H.S.C passing year'
 5. 'Program'
 6. 'Current Semester'
 7. 'Do you have meritorious scholarship ?'
 8. 'Do you use University transportation?'
 9. 'How many hour do you study daily?'
10. 'How many times do you seat for study in a day?'
11. 'What is your preferable learning mode?'
12. 'Do you use smart phone?'
13. 'Do you have personal Computer?'
14. 'How many hour do you spent daily in social media?'
15. 'Status of your English language proficiency'
16. 'Average attendance on class'
17. 'Did you ever fall in probation?'
18. 'Did you ever got suspension?'
19. 'Do you attend in teacher consultancy for any kind of academical problems?'
20. 'What are the skills do you have ?'
21. 'How many hour do you spent daily on your skill development?'
22. 'What is you interested area?'
23. 'What is your relationship status?'
24. 'Are you engaged with any co-curriculum activities?'
25. 'With whom you are living with?'
26. 'Do you have any health issues?'
27. 'What was your previous SGPA?'
28. 'Do you have any physical disabilities?'
29. 'What is your current CGPA?'
30. 'How many Credit did you have completed?'
31. 'What is your monthly family income?'

<b> Print exact Hasan columns </b>

In [13]:
print("HASAN COLUMNS")
print("=" * 60)

for i, col in enumerate(hasan.columns, 1):
    print(f"{i:2}. {repr(col)}")

HASAN COLUMNS
============================================================
 1. 'Department'
 2. 'Gender'
 3. 'HSC'
 4. 'SSC'
 5. 'Income'
 6. 'Hometown'
 7. 'Computer'
 8. 'Preparation'
 9. 'Gaming'
10. 'Attendance'
11. 'Job'
12. 'English'
13. 'Extra'
14. 'Semester'
15. 'Last'
16. 'Overall'

<b> Locate the missing value </b>

In [14]:
missing_rahman = rahman.isnull().sum()

print(
    missing_rahman[missing_rahman > 0]
)

What are the skills do you have ?    1
dtype: int64

<b> check Hasan data-set departments </b>

In [15]:
print("HASAN DEPARTMENT DISTRIBUTION")
print("=" * 50)

print(hasan["Department"].value_counts())

HASAN DEPARTMENT DISTRIBUTION
==================================================
Department
Computer Science and Engineering               443
English                                         14
Journalism, Communication and Media Studies     13
Political Science                                6
Business Administration                          5
Economics                                        4
Sociology                                        3
Law and Human Rights                             2
Public Health                                    2
Electrical and Electronic Engineering            1
Name: count, dtype: int64

<b> Inspect Rahman categorical values </b>

In [16]:
rahman_fields = [
    "Gender",
    "Current Semester",
    "How many hour do you study daily?",
    "Average attendance on class",
    "Are you engaged with any co-curriculum activities?",
    "What is your monthly family income?"
]

for col in rahman_fields:
    print("\n" + "=" * 70)
    print(col)
    print("=" * 70)
    print(rahman[col].value_counts(dropna=False))

======================================================================
Gender
======================================================================
Gender
Male      672
Female    522
Name: count, dtype: int64

======================================================================
Current Semester
======================================================================
Current Semester
2     211
11    166
8     149
3      99
9      98
10     90
4      77
5      65
7      64
1      62
6      56
12     21
14     12
13      9
15      5
22      3
17      2
21      1
18      1
19      1
16      1
24      1
Name: count, dtype: int64

======================================================================
How many hour do you study daily?
======================================================================
How many hour do you study daily?
2     315
3     307
4     181
1     156
5     124
6      61
7      19
8      15
0       9
9       4
10      2
13      1
Name: count, dtype: int64

======================================================================
Average attendance on class
======================================================================
Average attendance on class
100    357
90     182
95     107
80      93
98      53
      ...
31       1
64       1
24       1
81       1
53       1
Name: count, Length: 66, dtype: int64

======================================================================
Are you engaged with any co-curriculum activities?
======================================================================
Are you engaged with any co-curriculum activities?
No     689
Yes    505
Name: count, dtype: int64

======================================================================
What is your monthly family income?
======================================================================
What is your monthly family income?
40000     118
50000     109
30000     107
20000      85
25000      55
         ...
136000      1
137000      1
167000      1
180000      1
210000      1
Name: count, Length: 137, dtype: int64

<b> Inspect Hasan categorical values </b>

In [17]:
hasan_fields = [
    "Gender",
    "Semester",
    "Preparation",
    "Attendance",
    "Extra",
    "Income"
]

for col in hasan_fields:
    print("\n" + "=" * 70)
    print(col)
    print("=" * 70)
    print(hasan[col].value_counts(dropna=False).sort_index())

======================================================================
Gender
======================================================================
Gender
Female    165
Male      328
Name: count, dtype: int64

======================================================================
Semester
======================================================================
Semester
10th     57
11th     21
12th      4
2nd     183
3rd      35
4th      23
5th      33
6th      29
7th      24
8th      54
9th      30
Name: count, dtype: int64

======================================================================
Preparation
======================================================================
Preparation
0-1 Hour             218
2-3 Hours            228
More than 3 Hours     47
Name: count, dtype: int64

======================================================================
Attendance
======================================================================
Attendance
40%-59%       68
60%-79%      217
80%-100%     197
Below 40%     11
Name: count, dtype: int64

======================================================================
Extra
======================================================================
Extra
No     288
Yes    205
Name: count, dtype: int64

======================================================================
Income
======================================================================
Income
High (Above 50,000)                92
High (Above 50,000)                34
High (Above 50,000)                 3
Low (Below 15,000)                 61
Low (Below 15,000)                 13
Lower middle (15,000-30,000)      174
Lower middle (15,000-30,000)        5
Lower middle (15,000-30,000)        1
Upper middle (30,000-50,000)      109
Upper middle (30,000-50,000)        1
Name: count, dtype: int64

<b> Inspect previous and current academic performance </b>

In [18]:
print("RAHMAN ACADEMIC PERFORMANCE")
print("=" * 60)

print("\nPrevious SGPA:")
print(rahman["What was your previous SGPA?"].describe())

print("\nCurrent CGPA:")
print(rahman["What is your current CGPA?"].describe())


print("\nHASAN ACADEMIC PERFORMANCE")
print("=" * 60)

print("\nLast:")
print(hasan["Last"].describe())

print("\nOverall:")
print(hasan["Overall"].describe())

RAHMAN ACADEMIC PERFORMANCE
============================================================

Previous SGPA:
count    1194.000000
mean        2.683946
std         0.871589
min         0.000000
25%         2.200000
50%         2.680000
75%         3.380000
max         4.000000
Name: What was your previous SGPA?, dtype: float64

Current CGPA:
count    1194.000000
mean        3.165600
std         0.750127
min         0.000000
25%         2.900000
50%         3.210000
75%         3.670000
max         4.000000
Name: What is your current CGPA?, dtype: float64

HASAN ACADEMIC PERFORMANCE
============================================================

Last:
count    493.000000
mean       3.163888
std        0.641475
min        1.000000
25%        2.810000
50%        3.250000
75%        3.670000
max        4.000000
Name: Last, dtype: float64

Overall:
count    493.000000
mean       3.188383
std        0.591801
min        1.000000
25%        2.880000
50%        3.270000
75%        3.680000
max        4.000000
Name: Overall, dtype: float64

<b> Check data types </b>

In [19]:
columns_to_check = [
    "Current Semester",
    "How many hour do you study daily?",
    "Average attendance on class",
    "What was your previous SGPA?",
    "What is your current CGPA?"
]

print("RAHMAN")
for col in columns_to_check:
    print(f"{col}: {rahman[col].dtype}")

print("\nHASAN")
for col in [
    "Semester",
    "Preparation",
    "Attendance",
    "Last",
    "Overall"
]:
    print(f"{col}: {hasan[col].dtype}")

RAHMAN
Current Semester: int64
How many hour do you study daily?: int64
Average attendance on class: object
What was your previous SGPA?: float64
What is your current CGPA?: float64

HASAN
Semester: str
Preparation: str
Attendance: str
Last: float64
Overall: float64

<b> Create clean working copies </b>

In [20]:
rahman_clean = rahman.copy()
hasan_clean = hasan.copy()

print("Rahman working copy:", rahman_clean.shape)
print("Hasan working copy :", hasan_clean.shape)

Rahman working copy: (1194, 31)
Hasan working copy : (493, 16)

<b> Clean whitespace in Hasan text columns </b>

In [21]:
text_cols = hasan_clean.select_dtypes(include=["object", "string"]).columns

for col in text_cols:
    hasan_clean[col] = hasan_clean[col].str.strip()

print(hasan_clean["Income"].value_counts())

Income
Lower middle (15,000-30,000)    180
High (Above 50,000)             129
Upper middle (30,000-50,000)    110
Low (Below 15,000)               74
Name: count, dtype: int64

<b> Filter Hasan to Computer Science and Engineering </b>

In [22]:
hasan_cse = hasan_clean[
    hasan_clean["Department"] == "Computer Science and Engineering"
].copy()

print("Original Hasan rows:", len(hasan_clean))
print("CSE rows retained   :", len(hasan_cse))
print("Rows excluded       :", len(hasan_clean) - len(hasan_cse))

Original Hasan rows: 493
CSE rows retained   : 443
Rows excluded       : 50

<b> Inspect Rahman attendance values </b>

In [23]:
attendance_raw = rahman_clean["Average attendance on class"]

print("Data type:", attendance_raw.dtype)

print("\nPython value types:")
print(attendance_raw.map(type).value_counts())

attendance_numeric = pd.to_numeric(
    attendance_raw,
    errors="coerce"
)

print("\nValues that cannot be converted to numbers:")
print(
    attendance_raw[
        attendance_numeric.isna()
    ].value_counts(dropna=False)
)

Data type: object

Python value types:
Average attendance on class
<class 'int'>    1193
<class 'str'>       1
Name: count, dtype: int64

Values that cannot be converted to numbers:
Average attendance on class
94-98    1
Name: count, dtype: int64

<b> Inspect unusual Rahman semester values </b>

In [24]:
print("Rows with semester > 12:")

semester_gt_12 = rahman_clean[
    rahman_clean["Current Semester"] > 12
]

print("Count:", len(semester_gt_12))

semester_gt_12[
    [
        "Program",
        "Current Semester",
        "What was your previous SGPA?",
        "What is your current CGPA?"
    ]
]

Rows with semester > 12:
Count: 36

,Program,Current Semester,What was your previous SGPA?,What is your current CGPA?
103,BCSE,13,2.68,3.15
118,BCSE,13,2.20,2.66
119,BCSE,15,2.60,2.60
121,BCSE,14,2.87,2.99
124,BCSE,21,2.68,3.15
129,BCSE,14,2.98,2.96
138,BCSE,14,3.16,2.68
146,BCSE,13,2.68,3.15
151,BCSE,22,2.68,3.15
155,BCSE,15,2.68,3.15
187,BCSE,22,2.00,2.00
189,BCSE,15,3.42,3.02
190,BCSE,14,3.50,3.20
196,BCSE,18,3.10,2.84
206,BCSE,14,2.80,2.80
209,BCSE,15,2.11,2.54
233,BCSE,17,2.73,3.08
252,BCSE,14,2.79,2.84
276,BCSE,14,2.40,2.89
298,BCSE,14,3.25,2.95
307,BCSE,19,3.60,3.72
402,BCSE,14,2.59,2.56
430,BCSE,13,3.62,3.00
562,BCSE,13,2.66,2.76
578,BCSE,14,2.96,3.06
584,BCSE,13,2.65,2.97
587,BCSE,17,3.15,3.39
600,BCSE,14,2.75,2.88
618,BCSE,13,2.40,2.41
644,BCSE,22,3.22,2.83
651,BCSE,15,3.06,2.86
656,BCSE,16,3.51,3.51
680,BCSE,13,2.86,2.88
683,BCSE,14,2.76,2.64
705,BCSE,24,2.80,2.50
729,BCSE,13,2.55,2.65

<b> Inspect zero GPA values </b>

In [25]:
print("RAHMAN")
print(
    "Previous SGPA = 0:",
    (rahman_clean["What was your previous SGPA?"] == 0).sum()
)

print(
    "Current CGPA = 0:",
    (rahman_clean["What is your current CGPA?"] == 0).sum()
)

print("\nHASAN CSE")
print(
    "Last GPA = 0:",
    (hasan_cse["Last"] == 0).sum()
)

print(
    "Overall GPA = 0:",
    (hasan_cse["Overall"] == 0).sum()
)

RAHMAN
Previous SGPA = 0: 39
Current CGPA = 0: 39

HASAN CSE
Last GPA = 0: 0
Overall GPA = 0: 0

<b> Inspect Rahman zero-GPA rows </b>

In [26]:
rahman_zero_gpa = rahman_clean[
    (rahman_clean["What was your previous SGPA?"] == 0)
    |
    (rahman_clean["What is your current CGPA?"] == 0)
]

print("Zero-GPA related rows:", len(rahman_zero_gpa))

rahman_zero_gpa[
    [
        "Program",
        "Current Semester",
        "What was your previous SGPA?",
        "What is your current CGPA?"
    ]
]

Zero-GPA related rows: 41

,Program,Current Semester,What was your previous SGPA?,What is your current CGPA?
116,BCSE,11,0.00,2.53
173,BCSE,5,0.00,2.31
215,BCSE,2,4.00,0.00
218,BCSE,1,0.00,0.00
219,BCSE,2,3.68,0.00
236,BCSE,1,0.00,0.00
243,BCSE,1,0.00,0.00
249,BCSE,1,0.00,0.00
250,BCSE,1,0.00,0.00
251,BCSE,1,0.00,0.00
263,BCSE,1,0.00,0.00
269,BCSE,1,0.00,0.00
271,BCSE,1,0.00,0.00
274,BCSE,1,0.00,0.00
280,BCSE,1,0.00,0.00
282,BCSE,1,0.00,0.00
283,BCSE,1,0.00,0.00
318,BCSE,1,0.00,0.00
329,BCSE,1,0.00,0.00
338,BCSE,1,0.00,0.00
345,BCSE,1,0.00,0.00
385,BCSE,1,0.00,0.00
396,BCSE,1,0.00,0.00
403,BCSE,1,0.00,0.00
419,BCSE,1,0.00,0.00
428,BCSE,1,0.00,0.00
442,BCSE,1,0.00,0.00
446,BCSE,1,0.00,0.00
448,BCSE,1,0.00,0.00
481,BCSE,1,0.00,0.00
486,BCSE,1,0.00,0.00
491,BCSE,1,0.00,0.00
493,BCSE,1,0.00,0.00
496,BCSE,1,0.00,0.00
614,BCSE,1,0.00,0.00
625,BCSE,1,0.00,0.00
660,BCSE,1,0.00,0.00
695,BCSE,1,0.00,0.00
698,BCSE,1,0.00,0.00
699,BCSE,1,0.00,0.00
700,BCSE,1,0.00,0.00

<b> Remove unusable Rahman GPA records </b>

In [27]:
rahman_valid = rahman_clean[
    (rahman_clean["What was your previous SGPA?"] > 0)
    &
    (rahman_clean["What is your current CGPA?"] > 0)
].copy()

print("Original Rahman rows :", len(rahman_clean))
print("Rows removed         :", len(rahman_clean) - len(rahman_valid))
print("Valid Rahman rows    :", len(rahman_valid))

Original Rahman rows : 1194
Rows removed         : 41
Valid Rahman rows    : 1153

<b> Start the harmonised Rahman dataset </b>

In [28]:
rahman_h = pd.DataFrame()

print("Empty harmonised dataset created.")

Empty harmonised dataset created.

<b> Add gender </b>

In [29]:
rahman_h["gender"] = (
    rahman_valid["Gender"]
    .str.strip()
)

print(rahman_h["gender"].value_counts())

gender
Male      652
Female    501
Name: count, dtype: int64

<b> Add study stage </b>

In [30]:
def map_study_stage(value):
    value = int(value)

    if value <= 4:
        return "Early"
    elif value <= 8:
        return "Middle"
    else:
        return "Late"

In [31]:
rahman_h["study_stage"] = (
    rahman_valid["Current Semester"]
    .apply(map_study_stage)
)

print(rahman_h["study_stage"].value_counts())

study_stage
Late      410
Early     410
Middle    333
Name: count, dtype: int64

<b> Add study preparation </b>

In [32]:
def map_study_preparation(hours):
    if hours <= 1:
        return "0-1 Hour"
    elif hours <= 3:
        return "2-3 Hours"
    else:
        return "More than 3 Hours"

In [33]:
rahman_h["study_preparation"] = (
    rahman_valid["How many hour do you study daily?"]
    .apply(map_study_preparation)
)

print(rahman_h["study_preparation"].value_counts())

study_preparation
2-3 Hours            605
More than 3 Hours    390
0-1 Hour             158
Name: count, dtype: int64

<b> Clean Rahman attendance </b>

In [34]:
rahman_attendance = (
    rahman_valid["Average attendance on class"]
    .replace("94-98", 96)
)

rahman_attendance = pd.to_numeric(
    rahman_attendance,
    errors="coerce"
)

print("Conversion failures:", rahman_attendance.isna().sum())
print(rahman_attendance.describe())

Conversion failures: 0
count    1153.000000
mean       88.017346
std        15.451921
min         0.000000
25%        80.000000
50%        90.000000
75%       100.000000
max       100.000000
Name: Average attendance on class, dtype: float64

<B> Convert attendance into common categories </b>

In [35]:
def map_attendance(value):
    if value < 40:
        return "Below 40%"
    elif value < 60:
        return "40%-59%"
    elif value < 80:
        return "60%-79%"
    else:
        return "80%-100%"

In [36]:
rahman_h["attendance"] = (
    rahman_attendance
    .apply(map_attendance)
)

print(rahman_h["attendance"].value_counts())

attendance
80%-100%     948
60%-79%      135
40%-59%       49
Below 40%     21
Name: count, dtype: int64

<b> Add extracurricular participation </b>

In [37]:
rahman_h["extracurricular_participation"] = (
    rahman_valid[
        "Are you engaged with any co-curriculum activities?"
    ]
    .str.strip()
)

print(
    rahman_h["extracurricular_participation"]
    .value_counts()
)

extracurricular_participation
No     668
Yes    485
Name: count, dtype: int64

<b> Add family income </b>

In [38]:
def map_family_income(value):
    if value < 15000:
        return "Low"
    elif value < 30000:
        return "Lower middle"
    elif value <= 50000:
        return "Upper middle"
    else:
        return "High"

In [39]:
rahman_h["family_income"] = (
    rahman_valid["What is your monthly family income?"]
    .apply(map_family_income)
)

print(rahman_h["family_income"].value_counts())

family_income
High            512
Upper middle    440
Lower middle    171
Low              30
Name: count, dtype: int64

<b> Add previous academic performance </b>

In [40]:
rahman_h["previous_academic_performance"] = (
    rahman_valid["What was your previous SGPA?"]
)

print(
    rahman_h["previous_academic_performance"]
    .describe()
)

count    1153.000000
mean        2.772724
std         0.729781
min         0.131250
25%         2.330000
50%         2.680000
75%         3.390000
max         4.000000
Name: previous_academic_performance, dtype: float64

<b> Create Rahman academic-performance outcome </b>

Current CGPA is used only to construct the target variable and is not
included as a predictor.

The binary outcome follows the project proposal:

- **Higher Academic Performance:** GPA >= 3.0
- **Lower Academic Performance:** GPA < 3.0

This is an operational Higher/Lower academic-performance definition,
not an institutional Pass/Fail threshold.

In [41]:
rahman_h["outcome"] = (
    rahman_valid["What is your current CGPA?"]
    .apply(
        lambda x: "Higher" if x >= 3.0 else "Lower"
    )
)

print(rahman_h["outcome"].value_counts())

outcome
Higher    844
Lower     309
Name: count, dtype: int64

<b> Add source dataset </b>

In [42]:
rahman_h["source_dataset"] = "Rahman"

print(rahman_h["source_dataset"].value_counts())

source_dataset
Rahman    1153
Name: count, dtype: int64

<b> Validate the finished Rahman dataset </b>

In [43]:
print("Rahman harmonised shape:", rahman_h.shape)

print("\nColumns:")
for col in rahman_h.columns:
    print("-", col)

print("\nMissing values:")
print(rahman_h.isnull().sum())

print("\nOutcome distribution:")
print(rahman_h["outcome"].value_counts())

rahman_h.head()

Rahman harmonised shape: (1153, 9)

Columns:
- gender
- study_stage
- study_preparation
- attendance
- extracurricular_participation
- family_income
- previous_academic_performance
- outcome
- source_dataset

Missing values:
gender                           0
study_stage                      0
study_preparation                0
attendance                       0
extracurricular_participation    0
family_income                    0
previous_academic_performance    0
outcome                          0
source_dataset                   0
dtype: int64

Outcome distribution:
outcome
Higher    844
Lower     309
Name: count, dtype: int64

,gender,study_stage,study_preparation,attendance,extracurricular_participation,family_income,previous_academic_performance,outcome,source_dataset
0,Male,Late,2-3 Hours,80%-100%,Yes,Lower middle,2.68,Higher,Rahman
1,Male,Early,2-3 Hours,80%-100%,Yes,High,2.68,Higher,Rahman
2,Female,Middle,2-3 Hours,80%-100%,No,Upper middle,2.68,Higher,Rahman
3,Male,Early,0-1 Hour,80%-100%,No,High,2.68,Higher,Rahman
4,Male,Early,2-3 Hours,80%-100%,No,Upper middle,2.68,Higher,Rahman

<b>Start Hasan harmonised dataset</b>

In [44]:
hasan_h = pd.DataFrame()

print("Empty Hasan harmonised dataset created.")

Empty Hasan harmonised dataset created.

<b>Add gender</b>

In [45]:
hasan_h["gender"] = (
    hasan_cse["Gender"]
    .str.strip()
)

print(hasan_h["gender"].value_counts())

gender
Male      302
Female    141
Name: count, dtype: int64

<b> Convert Hasan semester to numeric </b>

In [46]:
hasan_semester = (
    hasan_cse["Semester"]
    .str.extract(r"(\d+)")[0]
    .astype(int)
)

print(hasan_semester.value_counts().sort_index())

0
2     172
3      25
4      16
5      31
6      26
7      20
8      54
9      29
10     52
11     18
Name: count, dtype: int64

<b>Add Hasan study stage</b>

In [47]:
hasan_h["study_stage"] = (
    hasan_semester
    .apply(map_study_stage)
)

print(hasan_h["study_stage"].value_counts())

study_stage
Early     213
Middle    131
Late       99
Name: count, dtype: int64

<b>Add attendance</b>

In [48]:
hasan_h["attendance"] = (
    hasan_cse["Attendance"]
    .str.strip()
)

print(hasan_h["attendance"].value_counts())

attendance
60%-79%      209
80%-100%     159
40%-59%       65
Below 40%     10
Name: count, dtype: int64

<b>Add extracurricular participation</b>

In [49]:
hasan_h["extracurricular_participation"] = (
    hasan_cse["Extra"]
    .str.strip()
)

print(
    hasan_h["extracurricular_participation"]
    .value_counts()
)

extracurricular_participation
No     279
Yes    164
Name: count, dtype: int64

<b>Add family income</b>

In [50]:
income_map = {
    "Low (Below 15,000)": "Low",
    "Lower middle (15,000-30,000)": "Lower middle",
    "Upper middle (30,000-50,000)": "Upper middle",
    "High (Above 50,000)": "High"
}

hasan_h["family_income"] = (
    hasan_cse["Income"]
    .map(income_map)
)

print(hasan_h["family_income"].value_counts())

print(
    "Unmapped income values:",
    hasan_h["family_income"].isna().sum()
)

family_income
Lower middle    156
High            123
Upper middle    100
Low              64
Name: count, dtype: int64
Unmapped income values: 0

<b>Add previous academic performance</b>

In [51]:
hasan_h["previous_academic_performance"] = (
    hasan_cse["Last"]
)

print(
    hasan_h["previous_academic_performance"]
    .describe()
)

count    443.000000
mean       3.121874
std        0.649071
min        1.000000
25%        2.750000
50%        3.250000
75%        3.640000
max        4.000000
Name: previous_academic_performance, dtype: float64

<b>Create Hasan academic-performance outcome </b>

Overall GPA is used only to construct the target variable and is not
included as a predictor.

The same common outcome definition is applied:

- **Higher Academic Performance:** GPA >= 3.0
- **Lower Academic Performance:** GPA < 3.0

In [52]:
hasan_h["outcome"] = (
    hasan_cse["Overall"]
    .apply(
        lambda x: "Higher" if x >= 3.0 else "Lower"
    )
)

print(hasan_h["outcome"].value_counts())

outcome
Higher    288
Lower     155
Name: count, dtype: int64

<b> study_preparation </b>

In [53]:
hasan_h["study_preparation"] = (
    hasan_cse["Preparation"]
    .str.strip()
)

print(hasan_h["study_preparation"].value_counts())

study_preparation
2-3 Hours            209
0-1 Hour             199
More than 3 Hours     35
Name: count, dtype: int64

<b>Add source</b>

In [54]:
hasan_h["source_dataset"] = "Hasan"

print(hasan_h["source_dataset"].value_counts())

source_dataset
Hasan    443
Name: count, dtype: int64

<b>Validate Hasan</b>

In [55]:
print("Hasan harmonised shape:", hasan_h.shape)

print("\nColumns:")
for col in hasan_h.columns:
    print("-", col)

print("\nMissing values:")
print(hasan_h.isnull().sum())

print("\nOutcome distribution:")
print(hasan_h["outcome"].value_counts())

hasan_h.head()

Hasan harmonised shape: (443, 9)

Columns:
- gender
- study_stage
- attendance
- extracurricular_participation
- family_income
- previous_academic_performance
- outcome
- study_preparation
- source_dataset

Missing values:
gender                           0
study_stage                      0
attendance                       0
extracurricular_participation    0
family_income                    0
previous_academic_performance    0
outcome                          0
study_preparation                0
source_dataset                   0
dtype: int64

Outcome distribution:
outcome
Higher    288
Lower     155
Name: count, dtype: int64

,gender,study_stage,attendance,extracurricular_participation,family_income,previous_academic_performance,outcome,study_preparation,source_dataset
5,Male,Early,Below 40%,No,Lower middle,1.00,Lower,0-1 Hour,Hasan
6,Male,Early,60%-79%,No,High,1.06,Lower,0-1 Hour,Hasan
7,Male,Late,80%-100%,Yes,Upper middle,2.95,Lower,2-3 Hours,Hasan
8,Male,Middle,Below 40%,Yes,Low,1.42,Lower,0-1 Hour,Hasan
9,Female,Early,Below 40%,No,Lower middle,1.50,Lower,0-1 Hour,Hasan

<b> Put both datasets in exactly the same column order </b>

In [56]:
common_columns = [
    "gender",
    "study_stage",
    "study_preparation",
    "attendance",
    "extracurricular_participation",
    "family_income",
    "previous_academic_performance",
    "outcome",
    "source_dataset"
]

rahman_h = rahman_h[common_columns]
hasan_h = hasan_h[common_columns]

print("Rahman columns identical:", rahman_h.columns.tolist() == common_columns)
print("Hasan columns identical :", hasan_h.columns.tolist() == common_columns)

Rahman columns identical: True
Hasan columns identical : True

<b>Final check before combining</b>

In [57]:
print("Rahman shape:", rahman_h.shape)
print("Hasan shape :", hasan_h.shape)

print("\nRahman missing values:", rahman_h.isnull().sum().sum())
print("Hasan missing values :", hasan_h.isnull().sum().sum())

Rahman shape: (1153, 9)
Hasan shape : (443, 9)

Rahman missing values: 0
Hasan missing values : 0

<b>Combine the datasets</b>

In [58]:
constructed_df = pd.concat(
    [rahman_h, hasan_h],
    ignore_index=True
)

print("Combined dataset shape:", constructed_df.shape)

Combined dataset shape: (1596, 9)

<b>Validate source contribution</b>

In [59]:
print(constructed_df["source_dataset"].value_counts())

source_dataset
Rahman    1153
Hasan      443
Name: count, dtype: int64

<b>Check final outcome distribution</b>

In [60]:
print(constructed_df["outcome"].value_counts())

print("\nOutcome percentages:")
print(
    constructed_df["outcome"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

outcome
Higher    1132
Lower      464
Name: count, dtype: int64

Outcome percentages:
outcome
Higher    70.93
Lower     29.07
Name: proportion, dtype: float64

<b>Check all harmonised categories</b>

In [61]:
categorical_columns = [
    "gender",
    "study_stage",
    "study_preparation",
    "attendance",
    "extracurricular_participation",
    "family_income"
]

for col in categorical_columns:
    print("\n" + "=" * 60)
    print(col)
    print("=" * 60)
    print(constructed_df[col].value_counts())

============================================================
gender
============================================================
gender
Male      954
Female    642
Name: count, dtype: int64

============================================================
study_stage
============================================================
study_stage
Early     623
Late      509
Middle    464
Name: count, dtype: int64

============================================================
study_preparation
============================================================
study_preparation
2-3 Hours            814
More than 3 Hours    425
0-1 Hour             357
Name: count, dtype: int64

============================================================
attendance
============================================================
attendance
80%-100%     1107
60%-79%       344
40%-59%       114
Below 40%      31
Name: count, dtype: int64

============================================================
extracurricular_participation
============================================================
extracurricular_participation
No     947
Yes    649
Name: count, dtype: int64

============================================================
family_income
============================================================
family_income
High            635
Upper middle    540
Lower middle    327
Low              94
Name: count, dtype: int64

<b>Final missing-value check</b>

In [62]:
print("Total missing values:")
print(constructed_df.isnull().sum())

print("\nTotal missing values in dataset:")
print(constructed_df.isnull().sum().sum())

Total missing values:
gender                           0
study_stage                      0
study_preparation                0
attendance                       0
extracurricular_participation    0
family_income                    0
previous_academic_performance    0
outcome                          0
source_dataset                   0
dtype: int64

Total missing values in dataset:
0

<b>Preview final constructed dataset</b>

In [63]:
constructed_df.head(10)

,gender,study_stage,study_preparation,attendance,extracurricular_participation,family_income,previous_academic_performance,outcome,source_dataset
0,Male,Late,2-3 Hours,80%-100%,Yes,Lower middle,2.68,Higher,Rahman
1,Male,Early,2-3 Hours,80%-100%,Yes,High,2.68,Higher,Rahman
2,Female,Middle,2-3 Hours,80%-100%,No,Upper middle,2.68,Higher,Rahman
3,Male,Early,0-1 Hour,80%-100%,No,High,2.68,Higher,Rahman
4,Male,Early,2-3 Hours,80%-100%,No,Upper middle,2.68,Higher,Rahman
5,Male,Early,2-3 Hours,80%-100%,Yes,Upper middle,2.68,Higher,Rahman
6,Male,Early,2-3 Hours,80%-100%,No,Lower middle,2.68,Higher,Rahman
7,Female,Early,2-3 Hours,80%-100%,No,Upper middle,3.80,Higher,Rahman
8,Male,Early,2-3 Hours,80%-100%,No,Lower middle,2.68,Higher,Rahman
9,Female,Early,More than 3 Hours,80%-100%,No,Lower middle,2.68,Higher,Rahman

In [66]:
# Define output location

output_dir = (
    project_root
    / "data"
    / "processed"
    / "constructed_dataset"
)

output_dir.mkdir(
    parents=True,
    exist_ok=True
)

output_path = (
    output_dir
    / "constructed_students.csv"
)

print("Output path:", output_path)

Output path: /Users/awais/Desktop/COMP8240_Project/data/processed/constructed_dataset/constructed_students.csv

In [67]:
constructed_df.to_csv(
    output_path,
    index=False
)

print("Saved to:", output_path)
print("Saved shape:", constructed_df.shape)

Saved to: /Users/awais/Desktop/COMP8240_Project/data/processed/constructed_dataset/constructed_students.csv
Saved shape: (1596, 9)

In [68]:
# Final verification of saved constructed dataset

saved_df = pd.read_csv(output_path)

assert saved_df.shape == (1596, 9)

assert saved_df["outcome"].value_counts().to_dict() == {
    "Higher": 1132,
    "Lower": 464
}

assert saved_df["source_dataset"].value_counts().to_dict() == {
    "Rahman": 1153,
    "Hasan": 443
}

assert saved_df.isnull().sum().sum() == 0

print("Final saved dataset verification passed.")
print("Shape:", saved_df.shape)
print("\nOutcome distribution:")
print(saved_df["outcome"].value_counts())

Final saved dataset verification passed.
Shape: (1596, 9)

Outcome distribution:
outcome
Higher    1132
Lower      464
Name: count, dtype: int64